project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Syllabus"
        contents:
          - Syllabus.qmd
      - section: "Handouts"
        contents:
        - Handout_1.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



