---
title: "Handout 2: La introducción a la lingüística generativa"
highlight-style: pygments
format:
  html: default
  pdf: default
  docx: default
---

# Handout 2

## La lengua como partes de nuestros genes

- Wernicke & Broca

- FOX P2

- Los animales

## La lingüística generativa

El enfoque de la lingüística generativa son los mecanismos internos de la mente. El comportamiento
lingüístico es (los textos, las manifestaciones del habla) solo son un conjunto de datos que
aportan evidencias acerca de estos mecanismos internos. 

La sintaxis generativa intenta descubrir los mecanismos internos que regulan la formación de la
oración.

**La gramática** es una teoría de la ***competencia*** (el conocimiento tácito que tiene el hablante de
su propia lengua), no un modelo de la ***actuación*** (el uso concreto que el hablante hace de su
competencia). 

**La competencia**: Una representación mental de una gramática que tiene un hablante de su
lengua. Es el conocimiento lingüístico de un hablante tal como está representado en su cerebro.

- Incluye: la fonética, la fonología, la morfología, la semántica, el léxico y la sintaxis (el enfoque de este curso).

- El Lenguaje es una parte de la composición biológica de nuestros cerebros.

**¿Qué es la lingüística?**

- Una suposición de la lingüística generativa: los seres humanos estamos preprogramados/genéticamente programados para adquirir y usar el lenguaje. A esta programa o receta se le llama **una gramática**.

- Además todos los seres humanos estamos tenemos esa gramática – **la gramática universal (Universal Grammar “UG”)**

## El Lenguaje como parte innata del cerebro/mente humana

1. Estamos genéticamente programados para adquirir y utilizar el lenguaje. Otros especies no
tienen el mismo lenguaje que los seres humanos. Los simios no pueden aprender un lenguaje humano.
Vea los casos de Nim Chimpsky y otros.

2. Las lesiones cerebrales en una parte del cerebro afecta el uso del lenguaje: afasia de Broca y afasia de Wernicke.

3. La facultad del lenguaje parece un módulo de la mente humana.  
  - Puede haber deficiencias que afectan al Lenguaje, pero no a las otras funciones cognitivas – El caso de la familia británica KE donde descubrieron un gen heredado por varias generaciones que afectaba el uso de morfemas funcionales: FOXP2.
  - Puede haber deficiencias que afectan otras funciones cognitivas, pero no el Lenguaje, como el caso de Christopher (que veremos por video).
  
https://www.youtube.com/watch?v=hVfyZVaH9ag
  
## Aprendizaje vs. adquisición

**Aprendizaje**: consiste en obtener conocimientos **de forma consciente**.
**Adquisición**: consiste en obtener conocimientos **de forma inconsciente**. 
    - La química se aprende, el lenguaje se adquiere.
    
**Una pregunta**: ¿Aprendemos nuestros idiomas de nuestros padres, profesores etc.? ¿Nos instruyen de forma explicita todo lo que sabemos sobre nuestro idioma?

**¿Cómo influye tu respuesta el siguiente diálogo?**
(de Pinker 1994, 268 – atribuido a Martin Braine)

*Child*: Want other one spoon, Daddy

*Adult*: You mean, you want the other spoon.

*Child*: Yes, I want other one spoon, please Daddy.

*Adult*: Can you say “the other spoon”?

*Child*: Other … one … spoon

*Adult*: Say “other”

*Child*: other

*Adult*: “spoon”

*Child*: spoon.

*Adult*: “other … spoon”

*Child*: other … spoon. Now give me other one spoon.

**Una observación**: Tenemos intuiciones sobre nuestras lenguas.  

**Una pregunta**: ¿Qué implica este conocimiento de nuestra lengua? ¿Nos enseñan todo de forma explicita? 


